[project]
name = "advent-of-code"
version = "12.25"
description = "ðŸŽ„"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "networkx>=3.6",
    "requests>=2.32.5",
    "z3-solver>=4.15.4.0",
]
